addSbtPlugin("org.scalameta"      % "sbt-scalafmt"    % "2.4.6")
addSbtPlugin("pl.project13.scala" % "sbt-jmh"         % "0.4.3")
addSbtPlugin("com.eed3si9n"       % "sbt-buildinfo"   % "0.11.0")
addSbtPlugin("org.scoverage"      % "sbt-scoverage"   % "2.0.3")
addSbtPlugin("org.scalameta"      % "sbt-mdoc"        % "2.3.3")
addSbtPlugin("ch.epfl.scala"      % "sbt-bloop"       % "1032048a")
addSbtPlugin("com.eed3si9n"       % "sbt-unidoc"      % "0.4.3")
addSbtPlugin("com.geirsson"       % "sbt-ci-release"  % "1.5.7")
addSbtPlugin("ch.epfl.scala"      % "sbt-scalafix"    % "0.10.3")
addSbtPlugin("dev.zio"            % "zio-sbt-website" % "0.0.0+84-6fd7d64e-SNAPSHOT")

resolvers += Resolver.sonatypeRepo("public")
